### ISSUE TITLE
Publish recent version to PyPI (graphql-core<3)

### ISSUE THREAD

**Issue by blazewicz** [graphql-python/aiohttp-graphql#16]
Current version available on PyPI requires `graphql-core>=2.0.dev`. Because of this I have to put restriction `graphql-core<3` in my project.

This was fixed in code, but not published yet.

**Comment by Cito** [comment]
I have prepared an improved v1.1.0, but we need @dfee for deployment on PyPI.

**Comment by KingDarBoja** [comment]
I have published the v1.0.0 on conda: [aiohtpp-graphql](https://anaconda.org/conda-forge/aiohttp-graphql)

It should have the `graphql-core` restriction as conda-forge let us modify the requirements before publishing.

**Comment by Cito** [comment]
Version 1.1.0 has now been published on PyPI.
