### ISSUE TITLE
GraphiQL not working with latest graphql-server-core

### ISSUE THREAD

**Issue by blazewicz** [graphql-python/aiohttp-graphql#17]
After this patch: https://github.com/graphql-python/graphql-server-core/commit/ad392b5 GraphqiQL is not rendered on GET requests even if configured with `graphiql=True`

**Comment by Cito** [comment]
Thanks for reporting. Do you set `return_promise=True`? Can you explain what you did exactly (how you set up your application) so that this issue can be reproduced?

**Comment by blazewicz** [comment]
Yes, this happens with AsyncioExecutor so `return_promise=True` is set.

You can see test case `test_graphiql_is_enabled[async]` is failing for current master.

NOTE:
to run tests with latest asyncio quick fix is required:

```diff
diff --git a/tests/conftest.py b/tests/conftest.py
index e765196..ef1925d 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -34,7 +34,8 @@ def app(event_loop, executor, view_kwargs):

 @pytest.fixture
 async def client(event_loop, app):
-    client = aiohttp.test_utils.TestClient(app, loop=event_loop)
+    server = aiohttp.test_utils.TestServer(app, loop=event_loop)
+    client = aiohttp.test_utils.TestClient(server, loop=event_loop)
     await client.start_server()
     yield client
     await client.close()
```

**Comment by Cito** [comment]
Are you sure you're using the current master? Because the tests are working for me locally and in [Travis](https://travis-ci.com/graphql-python/aiohttp-graphql/builds/145995077). Also, your diff does not match the current master.

**Comment by blazewicz** [comment]
Of course I was testing on master from my outdated fork, not upstream. This issue is already fixed then. Please choose if you want to close it or leave until fixed version is published to PyPI.

**Comment by Cito** [comment]
Ok. I wanted to get the latest version published on PyPI to avoid these kinds of problems, but so far I was not able to contact @dfee (the PyPI maintainer).
